<?php

namespace ContainerL4pjjlc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C77AWLPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.c77AWLP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.c77AWLP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ingredientLineRepository' => ['privates', 'App\\Repository\\IngredientLineRepository', 'getIngredientLineRepositoryService', true],
            'recipe' => ['privates', '.errored..service_locator.c77AWLP.App\\Entity\\Recipe', NULL, 'Cannot autowire service ".service_locator.c77AWLP": it references class "App\\Entity\\Recipe" but no such service exists.'],
            'stepLineRepository' => ['privates', 'App\\Repository\\StepLineRepository', 'getStepLineRepositoryService', true],
        ], [
            'ingredientLineRepository' => 'App\\Repository\\IngredientLineRepository',
            'recipe' => 'App\\Entity\\Recipe',
            'stepLineRepository' => 'App\\Repository\\StepLineRepository',
        ]);
    }
}
