<?php

namespace ContainerL4pjjlc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Co9UdPWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Co9UdPW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Co9UdPW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'unityRepository' => ['privates', 'App\\Repository\\UnityRepository', 'getUnityRepositoryService', true],
        ], [
            'unityRepository' => 'App\\Repository\\UnityRepository',
        ]);
    }
}
