<?php

namespace ContainerL4pjjlc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0KxPdQ1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0KxPdQ1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0KxPdQ1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'unityRepository' => ['privates', 'App\\Repository\\UnityRepository', 'getUnityRepositoryService', true],
        ], [
            'manager' => '?',
            'unityRepository' => 'App\\Repository\\UnityRepository',
        ]);
    }
}
