<?php

namespace ContainerL4pjjlc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BGZQc2YService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bGZQc2Y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bGZQc2Y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'likeRepo' => ['privates', 'App\\Repository\\RecipeLikeRepository', 'getRecipeLikeRepositoryService', true],
            'recipeRepo' => ['privates', 'App\\Repository\\RecipeRepository', 'getRecipeRepositoryService', true],
        ], [
            'likeRepo' => 'App\\Repository\\RecipeLikeRepository',
            'recipeRepo' => 'App\\Repository\\RecipeRepository',
        ]);
    }
}
