<?php

namespace ContainerL4pjjlc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUnityService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.9L0ZdzR.App\Entity\Unity' shared service.
     *
     * @return \App\Entity\Unity
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.9L0ZdzR": it references class "App\\Entity\\Unity" but no such service exists.');
    }
}
