<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL4pjjlc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL4pjjlc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerL4pjjlc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerL4pjjlc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerL4pjjlc\App_KernelDevDebugContainer([
    'container.build_hash' => 'L4pjjlc',
    'container.build_id' => '70c6c0aa',
    'container.build_time' => 1642094473,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerL4pjjlc');
